package pojo;
// Generated Oct 17, 2022 1:26:04 PM by Hibernate Tools 4.3.1

import dao.DAOJabatan;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 * TbJabatan generated by hbm2java
 */

@ManagedBean
public class TbJabatan  implements java.io.Serializable {


     private Integer jabatanId;
     private String staffId;
     private String jabatan;
     private String gaji;
     
    public void save_jabatan() {
    
        DAOJabatan addd = new DAOJabatan();
        addd.add_jabatan(this);
    
    }
    
     public List<TbJabatan> getAllRecordss() {
        
       DAOJabatan jb = new DAOJabatan();
       List<TbJabatan> lJb = jb.retreveTbJabatan();
       return lJb;
        
    }
     
    
    public String getByIdjb() {
    
        String jabatan_id = jabatanId.toString();
        DAOJabatan pro = new DAOJabatan();
        List<TbJabatan> lJb = pro.getbyID(jabatan_id);
        staffId = lJb.get(0).getStaffId();
        jabatan = lJb.get(0).getJabatan();
        gaji = lJb.get(0).getGaji();
        
        return "jabatan";
    
    }
    
    
    public String editt(){
    
        DAOJabatan jb = new DAOJabatan();
        jb.editJabatan(this);
        staffId = "";
        jabatan = "";
        gaji = "";
        return "jabatan";
    
    }
     
     
    public String deletee() {
    
        DAOJabatan jb = new DAOJabatan();
        jb.deleteJabatan(jabatanId);
        staffId = "";
        jabatan = "";
        gaji = "";
        return "jabatan";
    
    }
      
      
    public String resetee() {
    
        DAOJabatan jab = new DAOJabatan();
        jab.resetJabatan(this);
        staffId = "";
        jabatan = "";
        gaji = "";
        return "jabatan";
    
    }
     
     
     
     
     
     

    public TbJabatan() {
    }

    public TbJabatan(String staffId, String jabatan, String gaji) {
       this.staffId = staffId;
       this.jabatan = jabatan;
       this.gaji = gaji;
    }
   
    public Integer getJabatanId() {
        return this.jabatanId;
    }
    
    public void setJabatanId(Integer jabatanId) {
        this.jabatanId = jabatanId;
    }
    public String getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(String staffId) {
        this.staffId = staffId;
    }
    public String getJabatan() {
        return this.jabatan;
    }
    
    public void setJabatan(String jabatan) {
        this.jabatan = jabatan;
    }
    public String getGaji() {
        return this.gaji;
    }
    
    public void setGaji(String gaji) {
        this.gaji = gaji;
    }




}


